# -*- coding: utf-8 -*-
"""DAA 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaP76HvWLT5rVFZYrNHaQ18IE4bFoKxI

factorial code by using iterative and recursive methods
"""

import time

n = int(input("Enter a number: "))


def factorial_iterative(n):
    fact = 1
    for i in range(1, n + 1):
        fact = fact * i
    return fact


def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial_recursive(n - 1)


start = time.perf_counter()
result1 = factorial_iterative(n)
end = time.perf_counter()

iterative_time = end - start


start = time.perf_counter()
result2 = factorial_recursive(n)
end = time.perf_counter()

recursive_time = end - start


print("\nFactorial using Iterative Method:", result1)
print("Execution Time:", iterative_time, "seconds")

print("\nFactorial using Recursive Method:", result2)
print("Execution Time:", recursive_time, "seconds")


print("\nTime Complexity:")
print("Iterative Method: O(n)")
print("Recursive Method: O(n)")