# -*- coding: utf-8 -*-
"""DAA 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1howmyqUcVYXCIPXaXrsYIkmdap1JXToI
"""

import time

def make_change(coins, amount):

    dp = [float('inf')] * (amount + 1)


    dp[0] = 0


    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    if dp[amount] == float('inf'):
        return -1

    return dp[amount]



coins = list(map(int, input("Enter coin denominations: ").split()))
amount = int(input("Enter the amount: "))

start_time = time.perf_counter()

result = make_change(coins, amount)

end_time = time.perf_counter()

execution_time = end_time - start_time


if result == -1:
    print("Change cannot be made.")
else:
    print("Minimum number of coins required:", result)

print("Execution Time:", execution_time, "seconds")

print("Time Complexity: O(n × A)")
print("Space Complexity: O(A)")