# -*- coding: utf-8 -*-
"""DAA 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvZGDRIwzSk4k4Gz9mkAfRBziqNbzynA
"""

class Graph:
    def __init__(self, vertices):
        self.V = vertices
        self.edges = []

    def add_edge(self, u, v, weight):
        self.edges.append((weight, u, v))

    def find(self, parent, i):
        if parent[i] == i:
            return i
        return self.find(parent, parent[i])

    def union(self, parent, rank, x, y):
        root_x = self.find(parent, x)
        root_y = self.find(parent, y)

        if rank[root_x] < rank[root_y]:
            parent[root_x] = root_y
        elif rank[root_x] > rank[root_y]:
            parent[root_y] = root_x
        else:
            parent[root_y] = root_x
            rank[root_x] += 1

    def kruskal(self):

        self.edges.sort()

        parent = []
        rank = []

        for i in range(self.V):
            parent.append(i)
            rank.append(0)

        mst = []
        total_cost = 0

        for weight, u, v in self.edges:
            root_u = self.find(parent, u)
            root_v = self.find(parent, v)

            if root_u != root_v:
                mst.append((u, v, weight))
                total_cost += weight
                self.union(parent, rank, root_u, root_v)

            if len(mst) == self.V - 1:
                break

        print("Edges in Minimum Spanning Tree:")
        for u, v, weight in mst:
            print(f"{u} -- {v} = {weight}")

        print("Minimum Cost:", total_cost)


g = Graph(4)

g.add_edge(0, 1, 10)
g.add_edge(0, 2, 6)
g.add_edge(0, 3, 5)
g.add_edge(1, 3, 15)
g.add_edge(2, 3, 4)

g.kruskal()