# -*- coding: utf-8 -*-
"""DAA 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yab880IBK2ZWDMWmgwP9GV4erP-RGg5b
"""

graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

def dfs(graph, node, visited):
    if node not in visited:
        print(node, end=" ")
        visited.add(node)

        for neighbour in graph[node]:
            dfs(graph, neighbour, visited)

print("Graph:")
for node in graph:
    print(node, "->", graph[node])

print("\nDFS Traversal:")
visited = set()
dfs(graph, 'A', visited)

from collections import deque

graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

def bfs(graph, start):
    visited = set()
    queue = deque()

    visited.add(start)
    queue.append(start)

    while queue:
        node = queue.popleft()
        print(node, end=" ")

        for neighbour in graph[node]:
            if neighbour not in visited:
                visited.add(neighbour)
                queue.append(neighbour)

print("Graph:")
for node in graph:
    print(node, "->", graph[node])

print("\nBFS Traversal:")
bfs(graph, 'A')