# -*- coding: utf-8 -*-
"""DAA 9ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qn4VKmrUKgEr25XzlR932WxeYrqanK_Q
"""

INF = 9999999
V = 5
graph = [
    [0, 2, 0, 6, 0],
    [2, 0, 3, 8, 5],
    [0, 3, 0, 0, 7],
    [6, 8, 0, 0, 9],
    [0, 5, 7, 9, 0]
]

selected = [False] * V

selected[0] = True

print("Edges in Minimum Spanning Tree:")
print("Edge\tWeight")

total_weight = 0

for _ in range(V - 1):

    minimum = INF
    x = 0
    y = 0

    for i in range(V):
        if selected[i]:
            for j in range(V):
                if not selected[j] and graph[i][j] != 0:
                    if graph[i][j] < minimum:
                        minimum = graph[i][j]
                        x = i
                        y = j

    print(f"{x} - {y}\t{graph[x][y]}")

    total_weight += graph[x][y]
    selected[y] = True

print("Total weight of MST:", total_weight)